/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xmantis;

import java.io.File;
import javax.swing.JOptionPane;


/**
 *
 * @author Sargent
 */
public class MainWindow extends javax.swing.JFrame{

    /**
     * Creates new form MainWindow
     */
    public MainWindow(){
        initComponents();

        checkSaves();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_newCampian = new javax.swing.JDialog();
        newCampianDialog_label = new javax.swing.JLabel();
        newCampianDialog_nameLabel = new javax.swing.JLabel();
        newCampianDialog_nameField = new javax.swing.JTextField();
        newCampianDialog_createButton = new javax.swing.JButton();
        initWindow_xmantisLabel = new javax.swing.JLabel();
        initWindow_newCampianButton = new javax.swing.JButton();
        initWindow_loadCampianButton = new javax.swing.JButton();
        initWindow_delCampianButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_campians = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        initWindow_campianInfo = new javax.swing.JTextArea();

        newCampianDialog_label.setFont(new java.awt.Font("High Tower Text", 3, 36)); // NOI18N
        newCampianDialog_label.setText("New Campian");

        newCampianDialog_nameLabel.setFont(new java.awt.Font("High Tower Text", 1, 12)); // NOI18N
        newCampianDialog_nameLabel.setText("NAME");

        newCampianDialog_nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCampianDialog_nameFieldActionPerformed(evt);
            }
        });

        newCampianDialog_createButton.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        newCampianDialog_createButton.setText("CREATE");
        newCampianDialog_createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCampianDialog_createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_newCampianLayout = new javax.swing.GroupLayout(dialog_newCampian.getContentPane());
        dialog_newCampian.getContentPane().setLayout(dialog_newCampianLayout);
        dialog_newCampianLayout.setHorizontalGroup(
            dialog_newCampianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_newCampianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialog_newCampianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_newCampianLayout.createSequentialGroup()
                        .addComponent(newCampianDialog_label)
                        .addGap(18, 18, 18)
                        .addComponent(newCampianDialog_createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dialog_newCampianLayout.createSequentialGroup()
                        .addComponent(newCampianDialog_nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newCampianDialog_nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dialog_newCampianLayout.setVerticalGroup(
            dialog_newCampianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_newCampianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialog_newCampianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newCampianDialog_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newCampianDialog_createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(dialog_newCampianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCampianDialog_nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCampianDialog_nameLabel))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        initWindow_xmantisLabel.setFont(new java.awt.Font("High Tower Text", 3, 48)); // NOI18N
        initWindow_xmantisLabel.setText("XMANTIS ");

        initWindow_newCampianButton.setText("New");
        initWindow_newCampianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initWindow_newCampianButtonActionPerformed(evt);
            }
        });

        initWindow_loadCampianButton.setText("Load");

        initWindow_delCampianButton.setText("Delete");

        jScrollPane1.setViewportView(list_campians);

        initWindow_campianInfo.setEditable(false);
        initWindow_campianInfo.setColumns(20);
        initWindow_campianInfo.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        initWindow_campianInfo.setRows(5);
        initWindow_campianInfo.setTabSize(4);
        jScrollPane2.setViewportView(initWindow_campianInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(initWindow_xmantisLabel)
                                .addGap(0, 42, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(initWindow_newCampianButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(initWindow_loadCampianButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(initWindow_delCampianButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(initWindow_xmantisLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(initWindow_newCampianButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(initWindow_loadCampianButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(initWindow_delCampianButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initWindow_newCampianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initWindow_newCampianButtonActionPerformed
        /*
         * Opens a panel for creating a new campian. Uses information filled out in window
         * to create new Campian object and adds it to list_campians.
         */
        
        // Open newCampianDialog
        // 
    }//GEN-LAST:event_initWindow_newCampianButtonActionPerformed

    private void newCampianDialog_nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCampianDialog_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCampianDialog_nameFieldActionPerformed

    private void newCampianDialog_createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCampianDialog_createButtonActionPerformed
        if(newCampianDialog_nameField.getText().length() == 0)
            JOptionPane.showMessageDialog(this, "The name field cannot be empty.", "ERROR: Blank field", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_newCampianDialog_createButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try{
            for(javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels())
                if("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch(ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch(InstantiationException ex){
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch(IllegalAccessException ex){
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch(javax.swing.UnsupportedLookAndFeelException ex){
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                new MainWindow().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialog_newCampian;
    private javax.swing.JTextArea initWindow_campianInfo;
    private javax.swing.JButton initWindow_delCampianButton;
    private javax.swing.JButton initWindow_loadCampianButton;
    private javax.swing.JButton initWindow_newCampianButton;
    private javax.swing.JLabel initWindow_xmantisLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list_campians;
    private javax.swing.JButton newCampianDialog_createButton;
    private javax.swing.JLabel newCampianDialog_label;
    private javax.swing.JTextField newCampianDialog_nameField;
    private javax.swing.JLabel newCampianDialog_nameLabel;
    // End of variables declaration//GEN-END:variables

    private void checkSaves(){
        /*
         * First, checks if there is a save folder.
         * If there is no folder, one is created.
         * If there is, it checks for saved campians.
         * If no campians are present, displays "No saved campians" in
         * initWindow_campianInfo
         * Else, it calls refreshCampianList()
         */

        File dir = new File("saves\\");

        if(dir.exists())
            if(dir.listFiles().length > 0){
                initWindow_campianInfo.setText("Select a campian.");
                refreshCampianList();
            } else
                initWindow_campianInfo.setText("No saved campians.");
        else{
            Boolean created = dir.mkdir();
            initWindow_campianInfo.setText("No saved campians.");
        }
    }

    private void refreshCampianList(){
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
